### ISSUE TITLE
[Feature] Use `ubootOrangePi5`in nixpkgs instead 

### ISSUE THREAD

**Issue by ryan4yin** [dvdjv/socle#13]
Since https://github.com/NixOS/nixpkgs/pull/297946 has been merged, we now have `ubootOrangePi5` in nixpkgs, there is no need to build your own u-boot.

**Comment by dvdjv** [comment]
One fewer package to support. Thanks for pointing that out.

**Comment by dvdjv** [comment]
Fixed in #16
